import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "bEasy Cambodia: Cleaning & Pest",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [{ lang: "en" }, { lang: "km" }, { lang: "zh" }];
}

export default function LangLayout({
  children,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  return <>{children}</>;
}
