import type { Metadata } from "next";
import TelegramChatButton from "@/app/components/TelegramChatButton";

export const metadata: Metadata = {
  title: "bEasy Cambodia: Cleaning & Pest",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [{ lang: "en" }, { lang: "km" }, { lang: "zh" }];
}

export default async function LangLayout(props: unknown) {
  const { children } = props as { children: React.ReactNode };
  return (
    <>
      {children}
      {/* Telegram chat widget (client-only) */}
      <TelegramChatButton />
    </>
  );
}
