import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "bEasy Cambodia: Cleaning & Pest",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [{ lang: "en" }, { lang: "km" }, { lang: "zh" }];
}

export default async function LangLayout(
  props: Readonly<{
    children: React.ReactNode;
    params: { lang: string } | Promise<{ lang: string }>;
  }>
) {
  const { children } = props;
  return <>{children}</>;
}
